---
title: "nlmixr2 Citations"
date: "2024-02-09"
output: html_document
---

## Citations

In this document, we attempt to keep a list of published scientific work that has reported using `nlmixr` in some fashion. If you have used `nlmixr` or `nlmixr2` (or any `mixrverse` package) in your work, please let us know so we can add it to the list.

### Publications

#### 2019

Helmlinger G, Sokolov V, Peskov K, Hallow KM, Kosinsky Y, Voronova V, et al. **Quantitative Systems Pharmacology: An Exemplar Model-Building Workflow With Applications in Cardiovascular, Metabolic, and Oncology Drug Development.** CPT: Pharmacometrics & Systems Pharmacology. 2019;8(6):380–95. [10.1002/psp4.12426](https://onlinelibrary.wiley.com/doi/abs/10.1002/psp4.12426)

Fidler M, Wilkins JJ, Hooijmaijers R, Post TM, Schoemaker R, Trame MN, et al. **Nonlinear Mixed-Effects Model Development and Simulation Using nlmixr and Related R Open-Source Packages.** CPT: Pharmacometrics & Systems Pharmacology. 2019;8(9):621–33. [10.1002/psp4.12445](https://onlinelibrary.wiley.com/doi/abs/10.1002/psp4.12445)

Schoemaker R, Fidler M, Laveille C, Wilkins JJ, Hooijmaijers R, Post TM, et al. **Performance of the SAEM and FOCEI Algorithms in the Open-Source, Nonlinear Mixed Effect Modeling Tool nlmixr.** CPT: Pharmacometrics & Systems Pharmacology. 2019;8(12):923–30. [10.1002/psp4.12471](https://onlinelibrary.wiley.com/doi/abs/10.1002/psp4.12471)

#### 2020

Mwandigha LM, Fraser KJ, Racine-Poon A, Mouksassi MS, Ghani AC. **Power calculations for cluster randomized trials (CRTs) with right-truncated Poisson-distributed outcomes: a motivating example from a malaria vector control trial.** International Journal of Epidemiology. 2020 Jun 1;49(3):954–62. [10.1093/ije/dyz277](https://doi.org/10.1093/ije/dyz277)

#### 2021

Fidler M, Hooijmaijers R, Schoemaker R, Wilkins JJ, Xiong Y, Wang W. **R and nlmixr as a gateway between statistics and pharmacometrics.** CPT: Pharmacometrics & Systems Pharmacology. 2021;10(4):283–5. [10.1002/psp4.12618](https://onlinelibrary.wiley.com/doi/abs/10.1002/psp4.12618)

Lombard A, Mistry H, Aarons L, Ogungbenro K. **Dose individualisation in oncology using chemotherapy-induced neutropenia: Example of docetaxel in non-small cell lung cancer patients.** British Journal of Clinical Pharmacology. 2021;87(4):2053–63. [10.1111/bcp.14614](https://onlinelibrary.wiley.com/doi/abs/10.1111/bcp.14614) 

Lu J, Deng K, Zhang X, Liu G, Guan Y. **Neural-ODE for pharmacokinetics modeling and its advantage to alternative machine learning models in predicting new dosing regimens.** iScience. 2021 Jul 23;24(7). [10.1016/j.isci.2021.102804](https://www.cell.com/iscience/abstract/S2589-0042(21)00772-0)

Välitalo PAJ. **Pharmacometric estimation methods for aggregate data, including data simulated from other pharmacometric models.** J Pharmacokinet Pharmacodyn. 2021 Oct 1;48(5):623–38. [10.1007/s10928-021-09760-1](https://doi.org/10.1007/s10928-021-09760-1)

Goers R, Coman Schmid D, Jäggi VF, Paioni P, Okoniewski MJ, Parker A, et al. **SwissPKcdw – A clinical data warehouse for the optimization of pediatric dosing regimens.** CPT: Pharmacometrics & Systems Pharmacology. 2021;10(12):1578–87. [10.1002/psp4.12723](https://onlinelibrary.wiley.com/doi/abs/10.1002/psp4.12723)

Jaisser F, Tan X, Chi S, Liu J, Wang P, Bush M, et al. **The Non-Steroidal Mineralocorticoid Receptor Antagonist KBP-5074 Limits Albuminuria and has Improved Therapeutic Index Compared With Eplerenone in a Rat Model With Mineralocorticoid-Induced Renal Injury.** Frontiers in Pharmacology. 2021;12. [10.3389/fphar.2021.604928](https://doi.org/10.3389/fphar.2021.604928) 

Medhora M, Phadnis P, Narayanan J, Gasperetti T, Zielonka J, Moulder JE, et al. **Radiation Increases Bioavailability of Lisinopril, a Mitigator of Radiation-Induced Toxicities.** Frontiers in Pharmacology. 2021;12. [10.3389/fphar.2021.646076](https://www.frontiersin.org/journals/pharmacology/articles/10.3389/fphar.2021.646076)

#### 2022

Lee SY. **Bayesian Nonlinear Models for Repeated Measurement Data: An Overview, Implementation, and Applications.** Mathematics. 2022 Jan;10(6):898. [10.3390/math10060898](https://www.mdpi.com/2227-7390/10/6/898)

Aghamiri SS, Amin R, Helikar T. **Recent applications of quantitative systems pharmacology and machine learning models across diseases.** J Pharmacokinet Pharmacodyn. 2022 Feb 1;49(1):19–37. [10.1007/s10928-021-09790-9](https://doi.org/10.1007/s10928-021-09790-9)

Soeorg H, Sverrisdóttir E, Andersen M, Lund TM, Sessa M. **The PHARMACOM-EPI Framework for Integrating Pharmacometric Modelling Into Pharmacoepidemiological Research Using Real-World Data: Application to Assess Death Associated With Valproate.** Clinical Pharmacology & Therapeutics. 2022;111(4):840–56. [10.1002/cpt.2502](https://onlinelibrary.wiley.com/doi/abs/10.1002/cpt.2502)

Liakopoulos A, Aulin LBS, Buffoni M, Fragkiskou E, Coen van Hasselt JG, Rozen DE. **Allele-specific collateral and fitness effects determine the dynamics of fluoroquinolone resistance evolution. Proceedings of the National Academy of Sciences.** 2022 May 3;119(18):e2121768119. [10.1073/pnas.2121768119](https://www.pnas.org/doi/full/10.1073/pnas.2121768119) 

Mehta K, Guo T, Wallis RS, van der Graaf PH, van Hasselt JGC. **Quantitative Systems Pharmacology Modeling Framework of Autophagy in Tuberculosis: Application to Adjunctive Metformin Host-Directed Therapy. Antimicrobial Agents and Chemotherapy.** 2022 Jul 14;66(8):e00366-22. [10.1128/aac.00366-22](https://journals.asm.org/doi/10.1128/aac.00366-22)

Agyeman AA, You T, Chan PLS, Lonsdale DO, Hadjichrysanthou C, Mahungu T, et al. **Comparative assessment of viral dynamic models for SARS-CoV-2 for pharmacodynamic assessment in early treatment trials.** British Journal of Clinical Pharmacology. 2022;88(12):5428–33. [10.1111/bcp.15518](https://onlinelibrary.wiley.com/doi/abs/10.1111/bcp.15518)

Aulin LBS, Tandar ST, van Zijp T, van Ballegooie E, van der Graaf PH, Saleh MAA, et al. **Physiologically Based Modelling Framework for Prediction of Pulmonary Pharmacokinetics of Antimicrobial Target Site Concentrations.** Clin Pharmacokinet. 2022 Dec 1;61(12):1735–48. [10.1007/s40262-022-01186-3](https://doi.org/10.1007/s40262-022-01186-3)

Kloprogge F, Ortiz Canseco J, Phee L, Sadouki Z, Kipper K, Witney AA, et al. **Emergence of phenotypic and genotypic antimicrobial resistance in Mycobacterium tuberculosis.** Sci Rep. 2022 Dec 11;12(1):21429. [10.1038/s41598-022-25827-6](https://www.nature.com/articles/s41598-022-25827-6)

Voulgarelis D, Bulusu KC, Yates JWT. **Comparison of classical tumour growth models for patient derived and cell-line derived xenografts using the nonlinear mixed-effects framework.** Journal of Biological Dynamics. 2022 Dec 31;16(1):160–85. [10.1080/17513758.2022.2061615](https://doi.org/10.1080/17513758.2022.2061615)

#### 2023

Mak WY, Ooi QX, Cruz CV, Looi I, Yuen KH, Standing JF. **Assessment of the nlmixr R package for population pharmacokinetic modeling: A metformin case study.** British Journal of Clinical Pharmacology. 2023;89(1):330–9. [10.1111/bcp.15496](https://onlinelibrary.wiley.com/doi/abs/10.1111/bcp.15496)

Mehta K, Guo T, van der Graaf PH, van Hasselt JGC. **Predictions of Bedaquiline and Pretomanid Target Attainment in Lung Lesions of Tuberculosis Patients using Translational Minimal Physiologically Based Pharmacokinetic Modeling.** Clin Pharmacokinet. 2023 Mar 1;62(3):519–32. [10.1007/s40262-023-01217-7](https://doi.org/10.1007/s40262-023-01217-7)

Yang W, Mak W, Gwee A, Gu M, Wu Y, Shi Y, et al. **Establishment and Evaluation of a Parametric Population Pharmacokinetic Model Repository for Ganciclovir and Valganciclovir.** Pharmaceutics. 2023 Jul;15(7):1801. [10.3390/pharmaceutics15071801](https://www.mdpi.com/1999-4923/15/7/1801)

Ibrahim EIK, Karlsson MO, Friberg LE. **Assessment of ibrutinib scheduling on leukocyte, lymph node size and blood pressure dynamics in chronic lymphocytic leukemia through pharmacokinetic-pharmacodynamic models.** CPT: Pharmacometrics & Systems Pharmacology. 2023;12(9):1305–18. [10.1002/psp4.13010](https://onlinelibrary.wiley.com/doi/abs/10.1002/psp4.13010)

Zhang S, Agyeman AA, Hadjichrysanthou C, Standing JF. **SARS-CoV-2 viral dynamic modeling to inform model selection and timing and efficacy of antiviral therapy.** CPT: Pharmacometrics & Systems Pharmacology. 2023;12(10):1450–60. [10.1002/psp4.13022](https://onlinelibrary.wiley.com/doi/abs/10.1002/psp4.13022)

Barrett JS, Betourne A, Walls RL, Lasater K, Russell S, Borens A, et al. **The future of rare disease drug development: the rare disease cures accelerator data analytics platform (RDCA-DAP).** J Pharmacokinet Pharmacodyn. 2023 Dec 1;50(6):507–19. [10.1007/s10928-023-09859-7](https://doi.org/10.1007/s10928-023-09859-7)

#### 2024

Kovács L, Ferenci T, Gombos B, Füredi A, Rudas I, Szakács G, et al. **Positive Impulsive Control of Tumor Therapy—A Cyber-Medical Approach.** IEEE Transactions on Systems, Man, and Cybernetics: Systems. 2024 Jan;54(1):597–608. [10.1109/TSMC.2023.3315637](https://ieeexplore.ieee.org/abstract/document/10255720)

Lepak AJ, VanScoy B, Rubino C, Ambrose PG, Andes DR. **In vivo pharmacodynamic characterization of a next-generation polyene, SF001, in the invasive pulmonary aspergillosis mouse model.** Antimicrobial Agents and Chemotherapy. 2024 Feb 6;0(0):e01631-23. [10.1128/aac.01631-23](https://journals.asm.org/doi/10.1128/aac.01631-23)

### Conference Proceedings

#### 2016

Fidler M, Schoemaker R, Xiong Y, Wilkins J, Laveille C, Wang W. **W-66. nlmixr: an open-source package for pharmacometric modelling in R. Abstracts accepted for American Conference on Pharmacometrics 2016 (ACoP7).** J Pharmacokinet Pharmacodyn. 2016 43(S1):S115. [10.1007/s10928-016-9485-x](https://link.springer.com/article/10.1007/s10928-016-9485-x)

#### 2017 

Erhardt E, Jacobs T, Gasparini M. **Comparison of pharmacokinetic parameters estimated by the experimental R package 'nlmixr' and MONOLIX.** PAGE 2017 (Budapest, Hungary): [Abstr 7247](https://www.page-meeting.org/default.asp?abstract=7247)

Schoemaker R, Fidler M, Xiong Y, Wilkins J, Trame MN, Laveille C, Wang W. **T-012. nlmixr: an open-source package for pharmacometric modelling in R. Abstracts for American Conference on Pharmacometrics 2017 (ACoP8).** J Pharmacokinet Pharmacodyn. 2017 44(S1):S60. [10.1007/s10928-017-9536-y](https://link.springer.com/article/10.1007/s10928-017-9536-y)

Schoemaker R, Fidler M, Xiong Y, Wilkins J, Trame M, Laveille C, Wang W. **nlmixr: an open-source package for pharmacometric modelling in R.** PAGE 2017 (Budapest, Hungary): [Abstr 7102](https://www.page-meeting.org/default.asp?abstract=7102)

#### 2018

Bartels C, Bieth B, Dumortier T, Baltcheva I, Bhattacharya S, Ludwig I, Demin I, Gassem A, Renard D. **ggPMX: a toolbox to easily generate a comprehensive set of model diagnostic plots for population models.** PAGE 2018 (Montreux, Switzerland): [Abstr 8423](https://www.page-meeting.org/default.asp?abstract=8423)

Fidler M, Xiong Y, Schoemaker R, Wilkins J, Trame MN, Post T, Hooijmaijers R, Wang W. **W-058. Exploring inductive linearization in population pharmacokinetic and pharmacodynamic models. Abstracts for the Ninth American Conference on Pharmacometrics (ACoP9).** J Pharmacokinet Pharmacodyn. 2018 45(S1):S116. [10.1007/s10928-018-9606-9](https://link.springer.com/article/10.1007/s10928-018-9606-9)

Hooijmaijers R, Fidler M, Schoemaker R, Trame MN, Wang W, Wilkins J, Xiong Y, Post T. **ShinyMixR: A project-centric R/Shiny run management tool for nlmixr.** PAGE 2018 (Montreux, Switzerland): [Abstr 8452](https://www.page-meeting.org/default.asp?abstract=8452)

Erhardt EM, Ursino M, Jacobs T, Biewenga J, Gasparini M. **Bayesian knowledge integration for an in vitro–in vivo correlation (IVIVC) model.** PAGE 2018 (Montreux, Switzerland): [Abstr 8689](https://www.page-meeting.org/default.asp?abstract=8689)

#### 2019

Baltcheva I, Bartels C, Dumortier T, Bhattacharya S, Paule I, Ludwig I, Demin I, Gassem A, Renard D, Bieth B. **ggPMX: an open-source R package for pharmacometric model diagnostic plots.** PAGE 2019 (Stockholm, Sweden): [Abstr 9013](https://www.page-meeting.org/default.asp?abstract=9013)

Schoemaker S, Fidler M, Laveille C, Wilkins JJ, Hooijmaijers R, Post TM, Trame MN, Xiong Y, Wang W. **Performance of the SAEM and FOCEI algorithms in the open-source non-linear mixed effect modelling tool nlmixr.** PAGE 2019 (Stockholm, Sweden): [Abstr 8978](https://www.page-meeting.org/default.asp?abstract=8978) 

#### 2021

Aulin LBS, Liakopoulos A, Rozen DE, van Hasselt JGC. **Model-based design of innovative treatment strategies to suppress antimicrobial resistance using collateral sensitivity.** PAGE 2021 (Virtual): [Abstr 9792](https://www.page-meeting.org/default.asp?abstract=9792)

Ibrahim E, Karlsson MO, Friberg LE. **Pharmacokinetic-pharmacodynamic (PK-PD) modeling of leukocyte dynamics and lymph node size in chronic lymphocytic leukaemia patients treated with ibrutinib.** PAGE 2021 (Virtual): [Abstr 9682](https://www.page-meeting.org/default.asp?abstract=9682)

Jung WJ, Hwang T, Jung S, Savic RM, Chae JW, Yun HY. **Web based platform for clinical pharmacokinetic consultation service (CPCS) with Non-linear Mixed Effect Model.** PAGE 2021 (Virtual): [Abstr 9727](https://www.page-meeting.org/default.asp?abstract=9727)

Pham AD, van Hasselt JGC. **Modelling rate and extent of resistance development against colistin in Klebsiella pneumoniae.** PAGE 2021 (Virtual): [Abstr 9774](https://www.page-meeting.org/default.asp?abstract=9774)

Tran QT, Lee CH, Kim MG, Kim M, Kim H, Chae JW, Yun HY. **Overview of Korean Pharmacometrics Modeling Library and web-based pharmacometrics platform.** PAGE 2021 (Virtual): [Abstr 9865](https://www.page-meeting.org/default.asp?abstract=9865)

Vavilov S, Sokolov V, Zhudenkov K, Stolbov L, Peskov K. **Parameter estimation in nonlinear fixed-effects QSP models: benchmark of optimization methods.** PAGE 2021 (Virtual): [Abstr 9755](https://www.page-meeting.org/default.asp?abstract=9755)

#### 2022

Bieth B, Fidler M, Baltcheva I. **ggPMX: re-imagine diagnostics plots.** PAGE 2022 (Ljubljana, Slovenia): [Abstr 9998](https://www.page-meeting.org/default.asp?abstract=9998)

Liu C, Cojutti PG, Bussini L, Rosselli Del Turco E, Bartoletti M, Pea F. **Comparison of performances of the open-source R package “nlmixr” vs. Monolix for population pharmacokinetics of continuous infusion meropenem in patients with onco-hematological malignancies.** PAGE 2022 (Ljubljana, Slovenia): [Abstr 10210](https://www.page-meeting.org/default.asp?abstract=10210)

Nordgren R, Belin S, Yngman G, Huang Z, Carter SJ, Chen X, Qutishat O, Hamdan A, Wang S, Yang T, Assawasuwannakit P, Buatois S, Abrantes JA, Hooker AC, Karlsson MO. **Pharmpy: a versatile open-source library for pharmacometrics.** PAGE 2022 (Ljubljana, Slovenia): [Abstr 10096](https://www.page-meeting.org/default.asp?abstract=10096)

#### 2023

Cheng I, Solas C, Howley E, McGarrity O, Rajani K, Breuer J, Standing J, Kreins A. **Favipiravir pharmacokinetics in immunocompromised infants and children with chronic RNA viral infections.** PAGE 2023 (A Coruña, Spain): [Abstr 10570](https://www.page-meeting.org/default.asp?abstract=10570)

Codina MS, Pham AD, van Os W, al Jalali V, Matzneller P, Wölfl-Duchek M, Vychytil A, Reiter B, Stimpfl T, van Hasselt JG, Zeitlinger M. **Evaluating ceftazidime-avibactam exposure in patients undergoing automated peritoneal dialysis using population pharmacokinetic modelling.** PAGE 2023 (A Coruña, Spain): [Abstr 10707](https://www.page-meeting.org/default.asp?abstract=10707)

Combes FP, Fidler M, Ochsenbein D, Illis W, Subrahmanyam K, Ho Y-Y. **Benchmarking Industrial Computing Environments - Pharmacometrics Study (BICEPS)**. PAGE 2023 (A Coruña, Spain): [Abstr 10604](https://www.page-meeting.org/default.asp?abstract=10604)

Duong A, Marsot A. **NONMEM versus nlmixr2 : An example of external evaluation of gentamicin Pop-PK models**. PAGE 2023 (A Coruña, Spain): [Abstr 10602](https://www.page-meeting.org/default.asp?abstract=10602)

Fidler M, Denney WS, Harrold J, Hooijmaijers R, Schoemaker R, Taubert M, Trame M, Papathanasiou T, Wilkins J. **nlmixr2, rxode2 and NONMEM: interchangeable models using babelmixr2 and nonmem2rx.** PAGE 2023 (A Coruña, Spain): [Abstr 10313](https://www.page-meeting.org/default.asp?abstract=10313)

Huang Z, Standing JF, Kloprogge F. **Development and exploration of exhaustive, stepwise, and heuristic algorithms for automated population pharmacokinetic modelling.** PAGE 2023 (A Coruña, Spain): [Abstr 10704](https://www.page-meeting.org/default.asp?abstract=10704).

Jeon H, Sung T, Jung W, Chae J-W, Yun H-Y. **Construction of model-based PK-PD software platform using R package considering compatibility of nlme structured model**. PAGE 2023 (A Coruña, Spain): [Abstr 10432](https://www.page-meeting.org/default.asp?abstract=10432) 

Nordgren R, Belin S, Chen X, Borg J, Huang Z, Qutishat O, Shi K, Liu X, Wang S, Mohamed S, Mirasbekov S, Hooker AC, Karlsson MO. **Pharmpy: a versatile open-source library for pharmacometrics.** PAGE 2023 (A Coruña, Spain): [Abstr 10508](https://www.page-meeting.org/default.asp?abstract=10508)

Xu C, Yu J, Cao W, Lu H, Yao Z, Sun X, Zhang K, Luo J, Zheng Q, Zheng H. **PyMaS: population pharmacometric modeling in Python**. PAGE 2023 (A Coruña, Spain): [Abstr 10676](https://www.page-meeting.org/default.asp?abstract=10676)







